# Generated by Django 5.2.7 on 2026-06-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIpinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('ip_info', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=300)),
                ('query_string', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('visitor_ipinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitoripinfo')),
            ],
        ),
    ]
